/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoparqueo.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import proyectorparqueo.model.ReciboSalida;
import proyectorparqueo.model.ReciboSalidaDAO;

/**
 *
 * @author DIEGO
 */
public class FrmHistorialSalidas extends javax.swing.JFrame {
    private void cargarHistorialCompleto() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[] {
            "Placa", "Propietario", "Tipo", "Plan",
            "Hora ingreso", "Hora salida",
            "Minutos", "Horas", "Total", "Nota"
        }, 0
    );

    java.time.format.DateTimeFormatter f =
        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    // Pedimos todos los recibos a la BD
    java.util.List<ReciboSalida> lista = ReciboSalidaDAO.listarTodos();

    for (ReciboSalida r : lista) {
        if (r == null || r.getVehiculo() == null) continue;

        proyectorparqueo.model.vehiculo v = r.getVehiculo();

        modelo.addRow(new Object[] {
            v.getPlaca(),
            v.getPropietario(),
            v.getTipoVehiculo(),
            v.getTipoPlan(),
            (v.getHoraIngreso() == null) ? "" : v.getHoraIngreso().format(f),
            (r.getHoraSalida() == null) ? "" : r.getHoraSalida().format(f),
            r.getMinutos(),
            r.getHoras(),
            String.format("Q %.2f", r.getTotal()),
            r.getNota()
        });
    }

    tblHistorial.setModel(modelo);
}

    /**
     * Creates new form FrmHistorialSalidas
     */
    public FrmHistorialSalidas() {
        initComponents();
        cargarHistorialCompleto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarHistorial = new javax.swing.JButton();
        btnExportarCSV = new javax.swing.JButton();
        lblResumenHistorial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelDesde = new javax.swing.JLabel();
        jLebelHasta = new javax.swing.JLabel();
        btnFiltrarFecha = new javax.swing.JButton();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        lblTotalPeriodo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        lblTotalMotos = new javax.swing.JLabel();
        lblTotalEstudiantes = new javax.swing.JLabel();
        lblTotalCatedraticos = new javax.swing.JLabel();
        lblTotalFlat = new javax.swing.JLabel();
        lblTotalVariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCargarHistorial.setText("CARGAR HISTORIAL");
        btnCargarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarHistorialActionPerformed(evt);
            }
        });

        btnExportarCSV.setText("EXPORTAR CSV");
        btnExportarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCSVActionPerformed(evt);
            }
        });

        lblResumenHistorial.setText("RESUMEN HISTORIAL");

        jLabelDesde.setText("DESDE");

        jLebelHasta.setText("HASTA");

        btnFiltrarFecha.setText("FILTRAR POR FECHA");
        btnFiltrarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarFechaActionPerformed(evt);
            }
        });

        txtDesde.setText("DESDE");

        txtHasta.setText("HASTA");
        txtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHastaActionPerformed(evt);
            }
        });

        lblTotalPeriodo.setText("TOTAL PERIODO");

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblHistorial);

        lblTotalMotos.setText("TOTAL MOTOS");

        lblTotalEstudiantes.setText("TOTAL ESTUDIANTES");

        lblTotalCatedraticos.setText("TOTAL CATEDRATICOS");

        lblTotalFlat.setText("TOTAL FLAT");

        lblTotalVariable.setText("TOTAL VARIABLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCargarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExportarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblTotalPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalMotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblResumenHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabelDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDesde)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalEstudiantes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(lblTotalCatedraticos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLebelHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFiltrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalFlat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarHistorial)
                    .addComponent(btnExportarCSV)
                    .addComponent(btnFiltrarFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResumenHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDesde)
                    .addComponent(jLebelHasta)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPeriodo)
                    .addComponent(lblTotalMotos)
                    .addComponent(lblTotalEstudiantes)
                    .addComponent(lblTotalCatedraticos)
                    .addComponent(lblTotalFlat)
                    .addComponent(lblTotalVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarHistorialActionPerformed

        FrmHistorialSalidas f = new FrmHistorialSalidas();
        f.setLocationRelativeTo(this);
        f.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarHistorialActionPerformed

    private void btnFiltrarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarFechaActionPerformed

         String sDesde = txtDesde.getText().trim();
    String sHasta = txtHasta.getText().trim();

    if (sDesde.isEmpty() || sHasta.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingresa ambas fechas en formato yyyy-MM-dd.\nEjemplo: 2025-01-19"
        );
        return;
    }

    try {
        // 1) Parsear fechas (formato yyyy-MM-dd)
        java.time.LocalDate desde = java.time.LocalDate.parse(sDesde);
        java.time.LocalDate hasta = java.time.LocalDate.parse(sHasta);

        // 2) Convertir a rango de fecha/hora (inicio y fin de día)
        java.time.LocalDateTime dtDesde = desde.atStartOfDay();
        java.time.LocalDateTime dtHasta = hasta.atTime(23, 59, 59);

        // 3) Pedir los recibos a la BD dentro de ese rango
        java.util.List<proyectorparqueo.model.ReciboSalida> lista =
                proyectorparqueo.model.ReciboSalidaDAO.listarPorRango(dtDesde, dtHasta);

        // 4) Llenar tabla con los datos filtrados
        llenarTablaHistorial(lista);

        // 5) Actualizar todos los totales (período, motos, flat, etc.)
        actualizarTotalesPeriodo(lista);

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Formato de fecha inválido.\nUsa: yyyy-MM-dd (ej. 2025-01-19)\n\nDetalle: " + ex.getMessage()
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarFechaActionPerformed

    private void txtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHastaActionPerformed

    private void btnExportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCSVActionPerformed

         // 1) Verificar que la tabla tenga datos
    javax.swing.table.TableModel modelo = tblHistorial.getModel();
    int filas = modelo.getRowCount();
    int columnas = modelo.getColumnCount();

    if (filas == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No hay datos en la tabla para exportar.",
                "Exportar a CSV",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2) Elegir dónde guardar el archivo
    javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setDialogTitle("Guardar historial como CSV");
    chooser.setSelectedFile(new java.io.File("HistorialSalidas.csv"));

    int opcion = chooser.showSaveDialog(this);
    if (opcion != javax.swing.JFileChooser.APPROVE_OPTION) {
        return; // el usuario canceló
    }

    java.io.File archivo = chooser.getSelectedFile();
    // Asegurar extensión .csv
    String nombre = archivo.getAbsolutePath();
    if (!nombre.toLowerCase().endsWith(".csv")) {
        archivo = new java.io.File(nombre + ".csv");
    }

    // 3) Escribir el CSV
    try (java.io.PrintWriter pw = new java.io.PrintWriter(archivo, "UTF-8")) {

        // 3.1 Encabezados (nombres de columnas)
        StringBuilder sb = new StringBuilder();
        for (int c = 0; c < columnas; c++) {
            sb.append(modelo.getColumnName(c));
            if (c < columnas - 1) sb.append(",");  // separador
        }
        pw.println(sb.toString());

        // 3.2 Filas de datos
        for (int f = 0; f < filas; f++) {
            sb.setLength(0); // limpiar
            for (int c = 0; c < columnas; c++) {
                Object valor = modelo.getValueAt(f, c);
                String texto = (valor == null) ? "" : valor.toString();

                // opcional: envolver en comillas por si tiene comas
                if (texto.contains(",") || texto.contains("\"")) {
                    texto = texto.replace("\"", "\"\""); // escapar comillas
                    texto = "\"" + texto + "\"";
                }

                sb.append(texto);
                if (c < columnas - 1) sb.append(",");
            }
            pw.println(sb.toString());
        }

        pw.flush();

        javax.swing.JOptionPane.showMessageDialog(this,
                "Historial exportado correctamente a:\n" + archivo.getAbsolutePath(),
                "Exportar a CSV",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error al exportar a CSV:\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialSalidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarHistorial;
    private javax.swing.JButton btnExportarCSV;
    private javax.swing.JButton btnFiltrarFecha;
    private javax.swing.JLabel jLabelDesde;
    private javax.swing.JLabel jLebelHasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResumenHistorial;
    private javax.swing.JLabel lblTotalCatedraticos;
    private javax.swing.JLabel lblTotalEstudiantes;
    private javax.swing.JLabel lblTotalFlat;
    private javax.swing.JLabel lblTotalMotos;
    private javax.swing.JLabel lblTotalPeriodo;
    private javax.swing.JLabel lblTotalVariable;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables


    // Ajusta el paquete/clase según tu proyecto
private void llenarTablaHistorial(java.util.List<proyectorparqueo.model.ReciboSalida> lista) {
    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblHistorial.getModel();
    m.setRowCount(0);

    java.time.format.DateTimeFormatter fdt =
        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    for (proyectorparqueo.model.ReciboSalida r : lista) {
        proyectorparqueo.model.vehiculo v = r.getVehiculo();

        String placa       = (v == null) ? "" : v.getPlaca();
        String propietario = (v == null) ? "" : v.getPropietario();
        String tipo        = (v == null) ? "" : v.getTipoVehiculo();
        String plan        = (v == null) ? "" : v.getTipoPlan();

        String hIng = (v == null || v.getHoraIngreso() == null)
                      ? ""
                      : v.getHoraIngreso().format(fdt);

        String hSal = (r.getHoraSalida() == null)
                      ? ""
                      : r.getHoraSalida().format(fdt);

        m.addRow(new Object[]{
            placa,
            propietario,
            tipo,
            plan,
            hIng,
            hSal,
            r.getHoras(),
            String.format("Q %.2f", r.getTotal()),
            r.getNota()
        });
    }
}
    private void actualizarTotalesPeriodo(List<ReciboSalida> lista) {

    double totalGeneral = 0;
    double totalMotos = 0;
    double totalCarro = 0;
    double totalEst = 0;
    double totalCat = 0;
    double totalFlat = 0;
    double totalVar = 0;

    for (ReciboSalida r : lista) {

        double total = r.getTotal();
        totalGeneral += total;

        // Según tipo de vehículo
        if (r.getVehiculo().getTipoVehiculo().equalsIgnoreCase("MOTO"))
            totalMotos += total;
        else
            totalCarro += total;   // si quieres motos + carros separado

        // Según área (solo para reportes)
        String area = r.getVehiculo().getArea().toUpperCase();
        if (area.contains("ESTUDIANT"))
            totalEst += total;
        else if (area.contains("CATED"))
            totalCat += total;

        // Según plan
        String plan = r.getVehiculo().getTipoPlan().toUpperCase();
        if (plan.contains("FLAT"))
            totalFlat += total;
        else
            totalVar += total;
    }

    // Mostrar
    lblTotalPeriodo.setText("Q " + String.format("%.2f", totalGeneral));
    lblTotalMotos.setText("Q " + String.format("%.2f", totalMotos));
    lblTotalEstudiantes.setText("Q " + String.format("%.2f", totalEst));
    lblTotalCatedraticos.setText("Q " + String.format("%.2f", totalCat));
    lblTotalFlat.setText("Q " + String.format("%.2f", totalFlat));
    lblTotalVariable.setText("Q " + String.format("%.2f", totalVar));
}
    
}
