/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoparqueo.ui;

import proyectorparqueo.model.DatosApp;
import javax.swing.JOptionPane;
import proyectorparqueo.model.controlParqueo;
import proyectorparqueo.model.vehiculo;
/**
 *
 * @author DIEGO
 */

public class FrmIngreso extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmIngreso
     */
    public FrmIngreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblPropietario = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblPlan = new javax.swing.JLabel();
        cmbPlan = new javax.swing.JComboBox<>();
        lblArea = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnCargarCSV = new javax.swing.JButton();
        btnGuardarCSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlaca.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPlaca.setText("PLACA");

        txtPlaca.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        lblPropietario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPropietario.setText("PROPIETARIO:");

        txtPropietario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        lblTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTipo.setText("TIPO DE VEHICULO");

        cmbTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO", " ", " " }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lblPlan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPlan.setText("TIPO DE PLAN");

        cmbPlan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAN (FLAT)", "TARIFA VARIABLE" }));

        lblArea.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblArea.setText("ROL");

        cmbRol.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPropietario)
                    .addComponent(txtPlaca)
                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPlan, 0, 322, Short.MAX_VALUE)
                    .addComponent(cmbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnCargarCSV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCargarCSV.setText("CARGAR CSV");
        btnCargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCSVActionPerformed(evt);
            }
        });

        btnGuardarCSV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGuardarCSV.setText("GUARDAR CSV");
        btnGuardarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCSVActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR VEHICULO");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTitulo.setText("      REGISTRO  DE  VEHICULO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
            // 1) Leer campos
    String placa       = txtPlaca.getText().trim();
    String propietario = txtPropietario.getText().trim();
    String tipo        = (String) cmbTipo.getSelectedItem();   // "MOTO" o "CARRO"
    String plan        = (String) cmbPlan.getSelectedItem();   // "PLAN (FLAT)" o "VARIABLE"
    String rol         = (String) cmbRol.getSelectedItem();    // "ESTUDIANTE" o "CATEDRATICO"

    // 2) Validaciones básicas
    if (placa.isEmpty() || propietario.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa PLACA y PROPIETARIO.");
        return;
    }
    if (tipo == null || plan == null || rol == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona TIPO, PLAN y ROL.");
        return;
    }

    // 3) Reglas para asignar ÁREA
    String areaNombre;
    if ("MOTO".equalsIgnoreCase(tipo)) {
        areaNombre = "MOTOS";
    } else {
        areaNombre = "ESTUDIANTE".equalsIgnoreCase(rol) ? "ESTUDIANTES" : "CATEDRATICOS";
    }

    // 4) Validar cupo del área
    proyectorparqueo.model.Area area = proyectorparqueo.model.DatosApp.getAreaPorNombre(areaNombre);
    if (area == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Área inválida.");
        return;
    }
    if (area.estaLlena()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Área " + area.getNombre() + " sin cupo.");
        return;
    }
    
    rol = rol.trim().toUpperCase();
    if (rol.equals("ESTUDIANTES"))  rol = "ESTUDIANTE";
    if (rol.equals("CATEDRATICOS")) rol = "CATEDRATICO";

    // 5) Crear y registrar el vehículo en el modelo global
    vehiculo v = new vehiculo(placa, propietario, tipo, plan, true, rol, areaNombre);
    proyectorparqueo.model.DatosApp.PARQUEO.registrarVehiculo(v);

    // 6) Actualizar ocupación y alertar si ≥ 90%
    area.setOcupados(area.getOcupados() + 1);
    double porc = proyectorparqueo.model.DatosApp.porcentajeOcupacion(area);
    if (porc >= 90.0) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "ALERTA: " + area.getNombre() + " al " + String.format("%.1f", porc) + "% de ocupación."
        );
    }

    // 7) Mostrar resumen en el textarea
    java.time.format.DateTimeFormatter f = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    txtArea.append(String.format(
        "Placa: %-8s | Prop: %-18s | Tipo: %-5s | Plan: %-12s | Rol: %-12s | Área: %-13s | Ingreso: %s%n",
        v.getPlaca(), v.getPropietario(), v.getTipoVehiculo(), v.getTipoPlan(),
        v.getRol(), v.getArea(), v.getHoraIngreso().format(f)
    ));

    javax.swing.JOptionPane.showMessageDialog(this, "Vehículo registrado en área " + areaNombre + ".");
    
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGuardarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCSVActionPerformed

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar Archivo CSV.");

        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        try {
            proyectorparqueo.model.DatosApp.PARQUEO.guardarCSV(archivo.getAbsolutePath());
            javax.swing.JOptionPane.showMessageDialog(this,
                "Archivo guardado correctamente en:\n" + archivo.getAbsolutePath());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCSVActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        
        fileChooser.setDialogTitle("Seleccionar archivo CSV. ");
        
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION){
            java.io.File carpeta = fileChooser.getSelectedFile();
            java.util.List<java.io.File>listArchivos = new java.util.ArrayList<>();
            
            //Buscar recuersivamente las carpeyas
            buscarArchivosCSV(carpeta, listArchivos);
            if (!listArchivos.isEmpty()){
                txtArea.setText("");
                
                int cargados = 0;
                for (java.io.File archivo : listArchivos){
                    try {
                        txtArea.append("\n===Archivo: " + archivo.getName() + "===\n " );
                        
                        DatosApp.PARQUEO.cargarCSV(archivo.getAbsolutePath());
                        cargados ++;
                    } catch (Exception e){
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al leer " + archivo.getName());
                    }
                } 
                for (proyectorparqueo.model.vehiculo v : proyectorparqueo.model.DatosApp.PARQUEO.getVehiculos()) {
                    String area = (v.getArea() == null) ? "" : v.getArea();
                    String fh   = (v.getHoraIngreso() == null) ? "" : v.getHoraIngreso().toString();

                    txtArea.append(String.format(
                            "Placa: %-10s | Propietario: %-20s | Tipo: %-10s | Plan: %-15s | Rol: %-15s | Ingreso: %s%n",
                            v.getPlaca(),
                            v.getPropietario(),
                            v.getTipoVehiculo(),
                            v.getTipoPlan(),
                            area,
                            fh
                    ));
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Carga completada.\nSe cargaron " + cargados + "Archivos CSV correctamente. ");
            }else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron archivos CSV en esta carpeta ni subcarpeta");
            }
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnGuardarCSV;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbPlan;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables

private void buscarArchivosCSV(java.io.File carpeta, java.util.List<java.io.File> listaArchivos) {
    java.io.File[] archivos = carpeta.listFiles();
    if (archivos != null) {
        for (java.io.File archivo : archivos) {
            if (archivo.isDirectory()) {
                //  Busca recursivamente en las subcarpetas
                buscarArchivosCSV(archivo, listaArchivos);
            } else if (archivo.getName().toLowerCase().endsWith(".csv")) {
                //  Agrega solo los archivos .csv encontrados
                listaArchivos.add(archivo);
            }
        }
    }
}
}

