/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoparqueo.ui;

import proyectorparqueo.model.VehiculoDAO;
import proyectorparqueo.model.vehiculo;
/**
 *
 * @author DIEGO
 */

/////////////////RECIBE DATOS  USA PARQUEO.registrar vehiculo,    insertar en SQL

public class FrmIngreso extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmIngreso
     */
    public FrmIngreso() {
        initComponents();
        setLocationRelativeTo(null);
        actualizarEstadoCupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblPropietario = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblPlan = new javax.swing.JLabel();
        cmbPlan = new javax.swing.JComboBox<>();
        lblArea = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnCargarCSV = new javax.swing.JButton();
        btnGuardarCSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        lblEstadoCupos = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPlaca.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPlaca.setText("PLACA");

        txtPlaca.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        lblPropietario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPropietario.setText("PROPIETARIO:");

        txtPropietario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        lblTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTipo.setText("TIPO DE VEHICULO");

        cmbTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO", " ", " " }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lblPlan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblPlan.setText("TIPO DE PLAN");

        cmbPlan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLAN (FLAT)", "TARIFA VARIABLE" }));

        lblArea.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblArea.setText("ROL");

        cmbRol.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPropietario)
                    .addComponent(txtPlaca)
                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPlan, 0, 322, Short.MAX_VALUE)
                    .addComponent(cmbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnCargarCSV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCargarCSV.setText("CARGAR CSV");
        btnCargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCSVActionPerformed(evt);
            }
        });

        btnGuardarCSV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGuardarCSV.setText("GUARDAR CSV");
        btnGuardarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCSVActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR VEHICULO");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblEstadoCupos.setText("ESTADO DE CUPOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoCupos, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstadoCupos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTitulo.setText("      REGISTRO  DE  VEHICULO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
////////////////////// 1) Leer campos
        String placa       = txtPlaca.getText().trim();
        String propietario = txtPropietario.getText().trim();
        String tipo        = (String) cmbTipo.getSelectedItem();   // "MOTO" o "CARRO"
        String plan        = (String) cmbPlan.getSelectedItem();   // "PLAN (FLAT)" o "VARIABLE"
        String rol         = (String) cmbRol.getSelectedItem();    // "ESTUDIANTE" o "CATEDRATICO"

////////////////////// 2) Validaciones básicas
    if (placa.isEmpty() || propietario.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa PLACA y PROPIETARIO.");
        return;
    }
    if (tipo == null || plan == null || rol == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona TIPO, PLAN y ROL.");
        return;
    }

/////////////////////// 2.5) Verificar si la placa ya está registrada en el sistema

    proyectorparqueo.model.vehiculo yaDentro =
        proyectorparqueo.model.DatosApp.PARQUEO.buscarPorPlaca(placa);

    if (yaDentro != null) {
        javax.swing.JOptionPane.showMessageDialog(this,"La placa " + placa + " ya está registrada actualmente en el parqueo."
    );
    return; // no sigue registrando
}
    
////////////////////////// 3) Reglas para asignar ÁREA
    String areaNombre;
    if ("MOTO".equalsIgnoreCase(tipo)) {
        areaNombre = "MOTOS";
    } else {
        areaNombre = "ESTUDIANTE".equalsIgnoreCase(rol) ? "ESTUDIANTES" : "CATEDRATICOS";
    }

///////////////////////////// 4) Validar cupo del área
    proyectorparqueo.model.Area area = proyectorparqueo.model.DatosApp.getAreaPorNombre(areaNombre);
    if (area == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Área inválida.");
        return;
    }
    if (area.estaLlena()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Área " + area.getNombre() + " sin cupo.");
        return;
    }
    
    rol = rol.trim().toUpperCase();
    if (rol.equals("ESTUDIANTES"))  rol = "ESTUDIANTE";
    if (rol.equals("CATEDRATICOS")) rol = "CATEDRATICO";

///////////////////////////////// 5) Crear y registrar el vehículo en el modelo global
    vehiculo v = new vehiculo(placa, propietario, tipo, plan, true, rol, areaNombre);
    proyectorparqueo.model.DatosApp.PARQUEO.registrarVehiculo(v);
    VehiculoDAO.insertar(v);
    
/////////////////////////////////// Cobro inmediato si es PLAN FLAT
    if (plan.toUpperCase().contains("FLAT")) {
        double montoFlat;

    if (tipo.equalsIgnoreCase("MOTO")) {
        montoFlat = 25.0;   // o el valor que tu inge definió para moto FLAT
    } else {
        montoFlat = 40.0;   // o el valor para carro FLAT
    }

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "PLAN (FLAT) activado.\n" +
        "Debe pagar ahora: Q " + String.format("%.2f", montoFlat),
        "Cobro al ingreso",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}

//////////////////////////////// 6) Actualizar ocupación y alertar si ≥ 90%
    area.setOcupados(area.getOcupados() + 1);
    double porc = proyectorparqueo.model.DatosApp.porcentajeOcupacion(area);
    if (porc >= 90.0) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "ALERTA: " + area.getNombre() + " al " + String.format("%.1f", porc) + "% de ocupación."
        );
    }

//////////////////////////////// 7) Mostrar resumen en el textarea
    java.time.format.DateTimeFormatter f = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    txtArea.append(String.format(
        "Placa: %-8s | Prop: %-18s | Tipo: %-5s | Plan: %-12s | Rol: %-12s | Área: %-13s | Ingreso: %s%n",
        v.getPlaca(), v.getPropietario(), v.getTipoVehiculo(), v.getTipoPlan(),
        v.getRol(), v.getArea(), v.getHoraIngreso().format(f)
    ));

    javax.swing.JOptionPane.showMessageDialog(this, "Vehículo registrado en área " + areaNombre + ".");
    
    actualizarEstadoCupos();

    
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGuardarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCSVActionPerformed

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar Archivo CSV.");

        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        try {
            proyectorparqueo.model.DatosApp.PARQUEO.guardarCSV(archivo.getAbsolutePath());
            javax.swing.JOptionPane.showMessageDialog(this,
                "Archivo guardado correctamente en:\n" + archivo.getAbsolutePath());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCSVActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed

    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    fc.setDialogTitle("Seleccionar archivo(s) CSV o carpeta");
    fc.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
    fc.setMultiSelectionEnabled(true);
    fc.setAcceptAllFileFilterUsed(true);
    fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV", "csv"));

    int sel = fc.showOpenDialog(this);
    if (sel != javax.swing.JFileChooser.APPROVE_OPTION) return;

    java.util.List<java.io.File> archivos = new java.util.ArrayList<>();

    java.io.File elegido = fc.getSelectedFile();
    if (elegido.isDirectory()) {
        
////////////////////////// buscar recursivamente *.csv
        java.util.Deque<java.io.File> pila = new java.util.ArrayDeque<>();
        pila.push(elegido);
        while (!pila.isEmpty()) {
            java.io.File d = pila.pop();
            java.io.File[] hijos = d.listFiles();
            if (hijos == null) continue;
            for (java.io.File h : hijos) {
                if (h.isDirectory()) pila.push(h);
                else if (h.getName().toLowerCase().endsWith(".csv")) archivos.add(h);
            }
        }
    } else {
        // archivo suelto
        if (elegido.getName().toLowerCase().endsWith(".csv")) archivos.add(elegido);
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un CSV o una carpeta.");
            return;
        }
    }

    if (archivos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron CSV.");
        return;
    }

/////////////////////// Contadores
    int totalArchivos = 0, totalLineas = 0, aceptados = 0, rechazados = 0,
        duplicados = 0, sinCupo = 0, malFormados = 0;

///////////////////////// acumulador del dinero cobrado a planes FLAT
    double totalCobradoFlat = 0.0;

    txtArea.setText("");
    java.time.format.DateTimeFormatter iso = java.time.format.DateTimeFormatter.ISO_LOCAL_DATE_TIME;

    for (java.io.File csv : archivos) {
        totalArchivos++;
        txtArea.append("\n=== Archivo: " + csv.getAbsolutePath() + " ===\n");

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(csv))) {
            String linea;
            boolean primera = true;

            while ((linea = br.readLine()) != null) {
                totalLineas++;
                if (primera) {
                    primera = false;
                    // si parece header, saltar
                    if (linea.toLowerCase().contains("placa") && linea.contains(",")) continue;
                }
                if (linea.trim().isEmpty()) continue;

                String[] c = linea.split(",");
                for (int i = 0; i < c.length; i++) c[i] = c[i].trim();

                if (c.length < 4) { ///////////// min: placa, propietario, tipo, plan
                    malFormados++;
                    txtArea.append("  ! Línea mal formada: " + linea + "\n");
                    continue;
                }

////////////////////////// Campos básicos
                String placa = c[0];
                String propietario = c[1];
                String tipo = c[2].toUpperCase();            /// MOTO / CARRO
                String plan = c[3].toUpperCase();            /// PLAN (FLAT) / TARIFA VARIABLE u otros

////////////////////////////// Area y fecha (opcionales en tu CSV)
                String areaCSV  = (c.length >= 5) ? c[4].toUpperCase() : "";
                String fechaCSV = (c.length >= 6) ? c[5] : "";

/////////////////////////////// Normalizar plan posible sin espacio: "PLAN(FLAT)" -> "PLAN (FLAT)"
                if ("PLAN(FLAT)".equals(plan)) plan = "PLAN (FLAT)";

///////////////////////////// Derivar ROL/ÁREA coherentes con las reglas del proyecto
                String rol;
                String area;
                if ("MOTO".equals(tipo)) {
                    area = "MOTOS";
                    rol  = "ESTUDIANTE";
                } else { // CARRO
                    if ("ESTUDIANTES".equals(areaCSV) || "ESTUDIANTE".equals(areaCSV)) {
                        rol = "ESTUDIANTE";
                    } else if ("CATEDRATICOS".equals(areaCSV) || "CATEDRATICO".equals(areaCSV)) {
                        rol = "CATEDRATICO";
                    } else {
                        rol = "ESTUDIANTE";
                    }
                    area = "ESTUDIANTE".equals(rol) ? "ESTUDIANTES" : "CATEDRATICOS";
                }

////////////////////////// Evitar duplicados (ya adentro)
                if (proyectorparqueo.model.DatosApp.PARQUEO.buscarPorPlaca(placa) != null) {
                    duplicados++;
                    rechazados++;
                    txtArea.append("  Duplicado (ya adentro): " + placa + "\n");
                    continue;
                }

///////////////////////// Respetar capacidad del área
                proyectorparqueo.model.Area a = proyectorparqueo.model.DatosApp.getAreaPorNombre(area);
                if (a != null && a.estaLlena()) {
                    sinCupo++;
                    rechazados++;
                    txtArea.append("  x Sin cupo en " + area + " -> " + placa + "\n");
                    continue;
                }
////////////////////////// Construir objeto vehiculo

                proyectorparqueo.model.vehiculo v = new proyectorparqueo.model.vehiculo(        
                        placa, propietario, tipo, plan, true, rol, area
                );

/////////////////////////// Si venía fecha en el CSV, intenta usarla
                if (!fechaCSV.isEmpty()) {
                    try {
                        java.time.LocalDateTime hi = java.time.LocalDateTime.parse(fechaCSV, iso);
                        v.setHoraIngreso(hi);
                    } catch (Exception ignore) {
///////////////////////7// si falla, deja la hora actual
                    }
                }

////////////////////// 1) Registrar en memoria
                proyectorparqueo.model.DatosApp.PARQUEO.registrarVehiculo(v);
                if (a != null) a.setOcupados(a.getOcupados() + 1);

/////////////////////7 2) Guardar en SQL 
                try {
                    proyectorparqueo.model.VehiculoDAO.insertar(v);
                } catch (Exception ex) {

                System.err.println("Error guardando en SQL desde CSV (" + placa + "): " + ex.getMessage());
                }

/////////////////////////// 3) Mensaje en el textarea
                aceptados++;
                txtArea.append(String.format("  CARGADO %-8s | %-12s | %-15s | %-12s | AREA: %-13s | INGRESO: %s%n",
                        v.getPlaca(), v.getTipoVehiculo(), v.getTipoPlan(), rol, area, v.getHoraIngreso()
                ));

///////////////////////////// COBRO AL INGRESAR SI ES PLAN FLAT (Q40)
                if (plan.contains("FLAT")) {
                    double montoFlat = 40.0;
                    totalCobradoFlat += montoFlat;

                    txtArea.append(String.format(
                            "     -> PLAN FLAT cobrado al ingresar: Q%.2f a placa %s%n",
                            montoFlat, placa
                    ));
                }
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error leyendo: " + csv.getName() + "\n" + ex.getMessage());
        }
    }

///////////////////////////////// actualizar estado de cupos (con FLAT pendientes + adentro, como ya tienes)
    actualizarEstadoCupos();

    javax.swing.JOptionPane.showMessageDialog(this,
            "Carga finalizada.\n" +
            "Archivos: " + totalArchivos + "\n" +
            "Líneas leídas: " + totalLineas + "\n" +
            "Aceptados: " + aceptados + "\n" +
            "Rechazados: " + rechazados + "\n" +
            "   • Duplicados: " + duplicados + "\n" +
            "   • Sin cupo: " + sinCupo + "\n" +
            "   • Mal formados: " + malFormados + "\n" +
            "Total cobrado PLAN (FLAT): Q" + String.format("%.2f", totalCobradoFlat)
    );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnGuardarCSV;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbPlan;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblEstadoCupos;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables

    
/////////////////////////////// Devuelve un color CSS según el porcentaje de ocupación
private String colorCSS(double porc) {
    if (porc >= 90.0)      return "red";        // muy lleno
    else if (porc >= 80.0) return "orange";     // alto
    else if (porc >= 60.0) return "goldenrod";  // medio
    else                   return "green";      // tranquilo
}

    private void actualizarEstadoCupos() {
////////////////////////////////// capacidades por área 
    proyectorparqueo.model.Area aM = proyectorparqueo.model.DatosApp.getAreaPorNombre("MOTOS");
    proyectorparqueo.model.Area aE = proyectorparqueo.model.DatosApp.getAreaPorNombre("ESTUDIANTES");
    proyectorparqueo.model.Area aC = proyectorparqueo.model.DatosApp.getAreaPorNombre("CATEDRATICOS");

    int capMotos = (aM == null) ? 0 : aM.getCapacidad();
    int capEst   = (aE == null) ? 0 : aE.getCapacidad();
    int capCat   = (aC == null) ? 0 : aC.getCapacidad();

///////////////////////////////////// ocupación LÓGICA: adentro + FLAT pendientes 
    int ocupMotos = 0, ocupEst = 0, ocupCat = 0;

//////////////////////////// 1) Vehículos ADENTRO
    for (proyectorparqueo.model.vehiculo v :
            proyectorparqueo.model.DatosApp.PARQUEO.getVehiculos()) {

        String areaV = (v.getArea() == null) ? "" : v.getArea().trim().toUpperCase();

        if (areaV.equals("MOTOS"))             ocupMotos++;
        else if (areaV.equals("ESTUDIANTES"))  ocupEst++;
        else if (areaV.equals("CATEDRATICOS")) ocupCat++;
    }

/////////////////////////77// 2) Vehículos FLAT PENDIENTES (salieron hace ≤2h y aún ocupan su cupo)
    java.time.LocalDateTime ahora = java.time.LocalDateTime.now();

    for (proyectorparqueo.model.ReciboSalida r :
            proyectorparqueo.model.DatosApp.HISTORIAL_SALIDAS) {

        proyectorparqueo.model.vehiculo v = r.getVehiculo();
        if (v == null) continue;

        String planV = (v.getTipoPlan() == null) ? "" : v.getTipoPlan().trim().toUpperCase();
        String areaV = (v.getArea() == null)     ? "" : v.getArea().trim().toUpperCase();

        // Solo FLAT
        if (!planV.contains("FLAT")) continue;

//////////////////////////////// Si ya regresó, ya no cuenta como pendiente
        if (proyectorparqueo.model.DatosApp.PARQUEO.buscarPorPlaca(v.getPlaca()) != null) {
            continue;
        }

        long minutosFuera =
                java.time.Duration.between(r.getHoraSalida(), ahora).toMinutes();
        if (minutosFuera > 120) {
            continue; // ya no reserva lugar
        }

///////////////////////////7// Cuenta como ocupado en su área
        if (areaV.equals("MOTOS"))             ocupMotos++;
        else if (areaV.equals("ESTUDIANTES"))  ocupEst++;
        else if (areaV.equals("CATEDRATICOS")) ocupCat++;
    }

/////////////////////  porcentajes 
    double pMotos = (capMotos > 0) ? 100.0 * ocupMotos / capMotos : 0.0;
    double pEst   = (capEst   > 0) ? 100.0 * ocupEst   / capEst   : 0.0;
    double pCat   = (capCat   > 0) ? 100.0 * ocupCat   / capCat   : 0.0;

////////////////////// TEXTO CON HTML Y COLORES
    String html = String.format(
        "<html>" +
        "MOTOS: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "ESTUDIANTES: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "CATEDRATICOS: <span style='color:%s'>%d/%d (%.0f%%)</span>" +
        "</html>",
        colorCSS(pMotos), ocupMotos, capMotos, pMotos,
        colorCSS(pEst),   ocupEst,   capEst,   pEst,
        colorCSS(pCat),   ocupCat,   capCat,   pCat
    );

    lblEstadoCupos.setText(html);
}
    
private void buscarArchivosCSV(java.io.File carpeta, java.util.List<java.io.File> listaArchivos) {
    java.io.File[] archivos = carpeta.listFiles();
    if (archivos != null) {
        for (java.io.File archivo : archivos) {
            if (archivo.isDirectory()) {
////////////////////  Busca recursivamente en las subcarpetas
                buscarArchivosCSV(archivo, listaArchivos);
            } else if (archivo.getName().toLowerCase().endsWith(".csv")) {
///////////////////////  Agrega solo los archivos .csv encontrados
                listaArchivos.add(archivo);
            }
        }
    }
}
}

