/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoparqueo.ui;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private final DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Placa","Propietario","Tipo","Plan","Rol","Área","Ingreso", "Estado"}, 0);
    
    // Helper opcional: convierte null -> "" y a MAYÚSCULAS
    private String safeUpper(String s) {
        return (s == null) ? "" : s.trim().toUpperCase();
    }
    
    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        setLocationRelativeTo(null);      // centrar ventana (opcional)
        tblDatos.setModel(modelo);
        tblDatos.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(
            javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus,
            int row, int column) {

        java.awt.Component c = super.getTableCellRendererComponent(
                table, value, isSelected, hasFocus, row, column);

        int colEstado = 7; // índice de la columna "Estado"
        Object valEstado = table.getValueAt(row, colEstado);
        String estado = (valEstado == null) ? "" : valEstado.toString().trim().toUpperCase();

        if ("PENDIENTE".equals(estado)) {
            c.setBackground(new java.awt.Color(255, 255, 200)); // amarillo suave
        } else {
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
            } else {
                c.setBackground(java.awt.Color.WHITE);
            }
        }
        return c;
    }
});

////////////////////// Por si acaso, dejamos el plan EXACTO como lo usamos en el código:
        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] { "TODOS", "PLAN (FLAT)", "TARIFA VARIABLE" }
        ));

//////////////////////// Filtros: cada vez que cambie algo, refresca la tabla
        cmbTipo.addActionListener(e -> refrescarTabla());
        cmbPlan.addActionListener(e -> refrescarTabla());
        cmbRol.addActionListener(e -> refrescarTabla());
        btnRefrescar.addActionListener(e -> refrescarTabla());

///////////////////// Primer llenado
        refrescarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbPlan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();
        lblResumen = new javax.swing.JLabel();
        btnHistorialSQL = new javax.swing.JButton();
        btnExportarCSV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDatos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jScrollPane2.setViewportView(jScrollPane1);

        cmbTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "CARRO", "MOTO" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        cmbPlan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "PLAN(FLAT)", "TARIFA VARIABLE" }));
        cmbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("TIPO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("PLAN");

        cmbRol.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ESTUDIANTES", "CATEDRATICOS" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("ROL");

        btnRefrescar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        lblResumen.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblResumen.setText("PARA MOSTRAR TOTALES");

        btnHistorialSQL.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnHistorialSQL.setText("HISTORIAL SQL");
        btnHistorialSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialSQLActionPerformed(evt);
            }
        });

        btnExportarCSV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnExportarCSV.setText("EXPORTAR SCV");
        btnExportarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCSVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel4.setText("REPORTES ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel2)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(btnHistorialSQL)
                                .addGap(67, 67, 67)
                                .addComponent(btnExportarCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(415, 415, 415))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarCSV)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefrescar)
                    .addComponent(btnHistorialSQL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

        refrescarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void cmbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlanActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnHistorialSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialSQLActionPerformed
        // Cargar estado desde SQL primero (por si abriste recién el programa)
    proyectorparqueo.model.DatosApp.cargarDesdeSQL();

    // Luego mostrar el historial completo en la tabla
    cargarHistorialDesdeSQL();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialSQLActionPerformed

    private void btnExportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCSVActionPerformed

        exportarTablaACSV();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarCSV;
    private javax.swing.JButton btnHistorialSQL;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cmbPlan;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables


////////////////////// Devuelve el color en texto CSS según el porcentaje
private String colorCSS(double porcentaje) {
    if (porcentaje >= 90.0) return "#dc3545"; // rojo
    if (porcentaje >= 80.0) return "#fd7e14"; // naranja
    if (porcentaje >= 60.0) return "#ffc107"; // amarillo
    return "#28a745";                         // verde
}
////////////// En FrmReportes.java (fuera de cualquier otro método)

private void actualizarResumenPorAreasYTotales(
        int totalMostrados, int cMoto, int cCarro, int cFlat, int cVar, int totalSistema) {

///////////////// 1) Obtener áreas del modelo
    proyectorparqueo.model.Area aM = proyectorparqueo.model.DatosApp.getAreaPorNombre("MOTOS");
    proyectorparqueo.model.Area aE = proyectorparqueo.model.DatosApp.getAreaPorNombre("ESTUDIANTES");
    proyectorparqueo.model.Area aC = proyectorparqueo.model.DatosApp.getAreaPorNombre("CATEDRATICOS");

    int capM = (aM == null) ? 0 : aM.getCapacidad();
    int ocM  = (aM == null) ? 0 : aM.getOcupados();

    int capE = (aE == null) ? 0 : aE.getCapacidad();
    int ocE  = (aE == null) ? 0 : aE.getOcupados();

    int capC = (aC == null) ? 0 : aC.getCapacidad();
    int ocC  = (aC == null) ? 0 : aC.getOcupados();

    double pM = (capM > 0) ? 100.0 * ocM / capM : 0.0;
    double pE = (capE > 0) ? 100.0 * ocE / capE : 0.0;
    double pC = (capC > 0) ? 100.0 * ocC / capC : 0.0;

/////////////////////// 2) Construir texto HTML con colores por área
    String html = String.format(
        "<html>" +
        "Mostrados: %d | Motos: %d | Carros: %d | Flat: %d | Variable: %d | Total registrados: %d" +
        "<br/>" +
        "Motos: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "Estudiantes: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "Catedráticos: <span style='color:%s'>%d/%d (%.0f%%)</span>" +
        "</html>",
        totalMostrados, cMoto, cCarro, cFlat, cVar, totalSistema,
        colorCSS(pM), ocM, capM, pM,
        colorCSS(pE), ocE, capE, pE,
        colorCSS(pC), ocC, capC, pC
    );

    lblResumen.setText(html);   //////////////7 aquí se aplican los colores HTML
}
    private void refrescarTabla() {
///////////////////// filtros desde los combos
    String fTipo = safeUpper((String) cmbTipo.getSelectedItem());  // "TODOS"/"CARRO"/"MOTO"
    String fPlan = safeUpper((String) cmbPlan.getSelectedItem());  // "TODOS"/"PLAN (FLAT)"/"TARIFA VARIABLE"
    String fRol  = safeUpper((String) cmbRol.getSelectedItem());   // "TODOS"/"ESTUDIANTES"/"CATEDRATICOS"

////////////////7// Normalizar ROL para comparar con lo que guarda vehiculo
    if (fRol.equals("ESTUDIANTES"))  fRol = "ESTUDIANTE";
    if (fRol.equals("CATEDRATICOS")) fRol = "CATEDRATICO";

    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblDatos.getModel();
    m.setRowCount(0);   // limpiar tabla

    java.time.format.DateTimeFormatter fdt =
            java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

/////////// Contadores globales (solo de lo que se muestra)
    int cMoto = 0, cCarro = 0, cFlat = 0, cVar = 0;

////////////////// Contadores de cupos POR ÁREA (ADENTRO + PENDIENTES)
    int ocupMotos = 0, ocupEst = 0, ocupCat = 0;

    int pendientes = 0;   // FLAT PENDIENTES que todavía reservan espacio
    java.util.Set<String> yaAgregadas = new java.util.HashSet<>();

 ////////////////////// 1) Vehículos ADENTRO
    for (proyectorparqueo.model.vehiculo v : proyectorparqueo.model.DatosApp.PARQUEO.getVehiculos()) {

        String tipoV   = safeUpper(v.getTipoVehiculo());
        String planV   = safeUpper(v.getTipoPlan());
        String rolV    = safeUpper(v.getRol());
        String areaV   = safeUpper(v.getArea());
        String placaUp = safeUpper(v.getPlaca());

        boolean okTipo = fTipo.equals("TODOS") || tipoV.equals(fTipo);

        boolean okPlan;
        if (fPlan.equals("TODOS")) {
            okPlan = true;
        } else if (fPlan.contains("FLAT")) {
            okPlan = planV.contains("FLAT");
        } else if (fPlan.contains("VARIABLE")) {
            okPlan = planV.contains("VARIABLE");
        } else {
            okPlan = planV.equals(fPlan);
        }

        boolean okRol = fRol.equals("TODOS") || rolV.equals(fRol);

        if (!okTipo || !okPlan || !okRol) continue;

        m.addRow(new Object[]{
                v.getPlaca(),
                v.getPropietario(),
                v.getTipoVehiculo(),
                v.getTipoPlan(),
                v.getRol(),
                v.getArea(),
                (v.getHoraIngreso() == null) ? "" : v.getHoraIngreso().format(fdt),
                "ADENTRO"
        });

        yaAgregadas.add(placaUp);

        // contadores globales
        if (tipoV.equals("MOTO"))  cMoto++;
        if (tipoV.equals("CARRO")) cCarro++;
        if (planV.contains("FLAT"))     cFlat++;
        if (planV.contains("VARIABLE")) cVar++;

        // contadores por área (ADENTRO)
        if (areaV.equals("MOTOS"))            ocupMotos++;
        else if (areaV.equals("ESTUDIANTES"))  ocupEst++;
        else if (areaV.equals("CATEDRATICOS")) ocupCat++;
    }

    // 2) Vehículos FLAT PENDIENTES (salieron hace ≤2h)
    java.time.LocalDateTime ahora = java.time.LocalDateTime.now();

    for (proyectorparqueo.model.ReciboSalida r : proyectorparqueo.model.DatosApp.HISTORIAL_SALIDAS) {

        proyectorparqueo.model.vehiculo v = r.getVehiculo();
        if (v == null) continue;

        String placaUp = safeUpper(v.getPlaca());
        String planV   = safeUpper(v.getTipoPlan());
        String tipoV   = safeUpper(v.getTipoVehiculo());
        String rolV    = safeUpper(v.getRol());
        String areaV   = safeUpper(v.getArea());

/////////// Solo FLAT
        if (!planV.contains("FLAT")) continue;

//////////////// Si ya volvió a entrar, ya no es pendiente
        if (proyectorparqueo.model.DatosApp.PARQUEO.buscarPorPlaca(v.getPlaca()) != null) {
            continue;
        }

//////////////// Si ya lo agregamos por alguna razón, saltar
        if (yaAgregadas.contains(placaUp)) continue;

////////////////// ¿Sigue dentro de las 2 horas afuera?
        long minutosFuera = java.time.Duration.between(r.getHoraSalida(), ahora).toMinutes();
        if (minutosFuera > 120) continue;    // ya no debe aparecer

///////////////// Aplicar filtros
        boolean okTipo = fTipo.equals("TODOS") || tipoV.equals(fTipo);

        boolean okPlan;
        if (fPlan.equals("TODOS")) {
            okPlan = true;
        } else if (fPlan.contains("FLAT")) {
            okPlan = planV.contains("FLAT");
        } else if (fPlan.contains("VARIABLE")) {
            okPlan = planV.contains("VARIABLE");
        } else {
            okPlan = planV.equals(fPlan);
        }

        boolean okRol = fRol.equals("TODOS") || rolV.equals(fRol);

        if (!okTipo || !okPlan || !okRol) continue;

/////////////////////// Agregar fila como PENDIENTE (queda amarilla por el renderer)
        m.addRow(new Object[]{
                v.getPlaca(),
                v.getPropietario(),
                v.getTipoVehiculo(),
                v.getTipoPlan(),
                v.getRol(),
                v.getArea(),
                r.getHoraSalida().format(fdt),   // mostramos la hora de salida
                "PENDIENTE"
        });

        yaAgregadas.add(placaUp);
        pendientes++;

        // También cuentan como espacio ocupado en su área
        if (areaV.equals("MOTOS"))            ocupMotos++;
        else if (areaV.equals("ESTUDIANTES"))  ocupEst++;
        else if (areaV.equals("CATEDRATICOS")) ocupCat++;

        // y en globales:
        if (tipoV.equals("MOTO"))  cMoto++;
        if (tipoV.equals("CARRO")) cCarro++;
        if (planV.contains("FLAT"))     cFlat++;
        if (planV.contains("VARIABLE")) cVar++;
    }

    int adentro        = proyectorparqueo.model.DatosApp.PARQUEO.getVehiculos().size();
    int totalMostrados = m.getRowCount();
    int totalLogico    = adentro + pendientes; // lo que realmente ocupa espacio (adentro + pendientes)

/////////////// capacidades de cada área 
    proyectorparqueo.model.Area aM = proyectorparqueo.model.DatosApp.getAreaPorNombre("MOTOS");
    proyectorparqueo.model.Area aE = proyectorparqueo.model.DatosApp.getAreaPorNombre("ESTUDIANTES");
    proyectorparqueo.model.Area aC = proyectorparqueo.model.DatosApp.getAreaPorNombre("CATEDRATICOS");

    int capMotos = (aM == null) ? 0 : aM.getCapacidad();
    int capEst   = (aE == null) ? 0 : aE.getCapacidad();
    int capCat   = (aC == null) ? 0 : aC.getCapacidad();

    double pMotos = (capMotos > 0) ? 100.0 * ocupMotos / capMotos : 0;
    double pEst   = (capEst   > 0) ? 100.0 * ocupEst   / capEst   : 0;
    double pCat   = (capCat   > 0) ? 100.0 * ocupCat   / capCat   : 0;

    // Resumen con COLORES (HTML)
    String resumenHtml = String.format(
        "<html>" +
        "Mostrados: %d | Motos: %d | Carros: %d | Flat: %d | Variable: %d | Total lógicos: %d" +
        "<br/>" +
        "Motos: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "Estudiantes: <span style='color:%s'>%d/%d (%.0f%%)</span> &nbsp; | " +
        "Catedráticos: <span style='color:%s'>%d/%d (%.0f%%)</span>" +
        "</html>",
        totalMostrados, cMoto, cCarro, cFlat, cVar, totalLogico,
        colorCSS(pMotos), ocupMotos, capMotos, pMotos,
        colorCSS(pEst),   ocupEst,   capEst,   pEst,
        colorCSS(pCat),   ocupCat,   capCat,   pCat
    );

    lblResumen.setText(resumenHtml);
}
   
    private void cargarHistorialDesdeSQL() {
///////////// Limpiar la tabla
    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblDatos.getModel();
    m.setRowCount(0);

    java.time.format.DateTimeFormatter fdt =
        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    double totalGeneral = 0.0;
    int    contFilas    = 0;

//////////////// Pedimos TODOS los recibos de la BD
    java.util.List<proyectorparqueo.model.ReciboSalida> lista =
            proyectorparqueo.model.ReciboSalidaDAO.listarTodos();

    for (proyectorparqueo.model.ReciboSalida r : lista) {
        if (r == null || r.getVehiculo() == null) continue;

        proyectorparqueo.model.vehiculo v = r.getVehiculo();

        m.addRow(new Object[]{
            v.getPlaca(),
            v.getPropietario(),
            v.getTipoVehiculo(),
            v.getTipoPlan(),
            v.getRol(),                      // en SQL no guardamos rol real, pero sirve para reporte
            v.getArea(),                     // idem
            r.getHoraSalida().format(fdt),   // aquí mostramos la HORA DE SALIDA
            String.format("HISTORIAL (Q %.2f)", r.getTotal())
        });

        totalGeneral += r.getTotal();
        contFilas++;
    }

    lblResumen.setText(String.format(
        "HISTORIAL: %d registros | Total recaudado: Q %.2f",
        contFilas, totalGeneral
    ));
}
    private void exportarTablaACSV() {
    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    fc.setDialogTitle("Guardar reporte en CSV");
    fc.setSelectedFile(new java.io.File("reporte_parqueo.csv"));

    int sel = fc.showSaveDialog(this);
    if (sel != javax.swing.JFileChooser.APPROVE_OPTION) {
        return;
    }

    java.io.File archivo = fc.getSelectedFile();

    try (java.io.PrintWriter pw = new java.io.PrintWriter(
            new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream(archivo),
                    java.nio.charset.StandardCharsets.UTF_8
            ))) {

        javax.swing.table.TableModel modelo = tblDatos.getModel();
        int cols = modelo.getColumnCount();
        int filas = modelo.getRowCount();

        // Encabezados
        for (int c = 0; c < cols; c++) {
            String nombreCol = modelo.getColumnName(c);
            pw.print(escaparCSV(nombreCol));
            if (c < cols - 1) pw.print(",");
        }
        pw.println();

        // Filas
        for (int f = 0; f < filas; f++) {
            for (int c = 0; c < cols; c++) {
                Object val = modelo.getValueAt(f, c);
                String texto = (val == null) ? "" : val.toString();
                pw.print(escaparCSV(texto));
                if (c < cols - 1) pw.print(",");
            }
            pw.println();
        }

        pw.flush();
        javax.swing.JOptionPane.showMessageDialog(this,
                "Reporte exportado correctamente a:\n" + archivo.getAbsolutePath());

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error al exportar CSV:\n" + ex.getMessage());
    }
}

private String escaparCSV(String s) {
    if (s == null) return "";
    boolean necesita = s.contains(",") || s.contains("\"") || s.contains("\n") || s.contains("\r");
    if (necesita) {
        s = s.replace("\"", "\"\"");
        return "\"" + s + "\"";
    } else {
        return s;
    }
}
}