/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoparqueo.ui;

import proyectorparqueo.model.DatosApp;
import javax.swing.JOptionPane;
import proyectorparqueo.model.VehiculoDAO;

/**
 *
 * @author DIEGO
 */
public class FrmReingreso extends javax.swing.JFrame {

    /**
     * Creates new form FrmReingreso
     */
    public FrmReingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloR = new javax.swing.JLabel();
        lblPlacaR = new javax.swing.JLabel();
        txtPlacaR = new javax.swing.JTextField();
        btnBuscarR = new javax.swing.JButton();
        btnLimpiarR = new javax.swing.JButton();
        btnReingresar = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloR.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTituloR.setText("REGISTRO DE VEHICULO");

        lblPlacaR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        lblPlacaR.setText("PLACA");

        btnBuscarR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnBuscarR.setText("BUSCAR");
        btnBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRActionPerformed(evt);
            }
        });

        btnLimpiarR.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnLimpiarR.setText("LIMPIAR");

        btnReingresar.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnReingresar.setText("REINGRESAR");
        btnReingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReingresarActionPerformed(evt);
            }
        });

        txtAreaR.setColumns(20);
        txtAreaR.setRows(5);
        jScrollPane1.setViewportView(txtAreaR);

        JScrollPane.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPlacaR, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnReingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlacaR, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(btnBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(btnLimpiarR, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacaR)
                    .addComponent(txtPlacaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarR)
                    .addComponent(btnLimpiarR)
                    .addComponent(btnReingresar))
                .addGap(18, 18, 18)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRActionPerformed

         String placa = txtPlacaR.getText().trim();
    if (placa.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa una placa.");
        return;
    }

//////////////////// Usar la última salida registrada
    proyectorparqueo.model.ReciboSalida r = proyectorparqueo.model.DatosApp.ultimaSalidaDe(placa);

    if (r == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay registro previo de salida para esta placa.");
        txtAreaR.setText("");
        btnReingresar.setEnabled(false);
        return;
    }

    proyectorparqueo.model.vehiculo v = r.getVehiculo();
    java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
    long minutos = java.time.Duration.between(r.getHoraSalida(), ahora).toMinutes();

/////////////////////// Normalizar plan
    String plan = (v.getTipoPlan() == null) ? "" : v.getTipoPlan().toUpperCase();

    boolean puedeReingresarGratis = false;
    String mensaje;

    if (plan.contains("FLAT")) {
        if (minutos <= 120) {
            puedeReingresarGratis = true;
            mensaje = " PLAN (FLAT): reingreso GRATUITO (dentro de las 2 horas).";
        } else {
            mensaje = "️ PLAN (FLAT): han pasado más de 2 horas.\n"
                    + "El plan se considera vencido, se cobrará nuevamente en un nuevo ingreso.";
        }
    } else {
        mensaje = "🔸 PLAN VARIABLE: se cobrará normalmente al salir.";
    }

    txtAreaR.setText(String.format(
        "PLACA: %s%n" +
        "PROPIETARIO: %s%n" +
        "TIPO: %s%n" +
        "PLAN: %s%n" +
        "ROL: %s%n" +
        "AREA: %s%n" +
        "HORA SALIDA: %s%n" +
        "TIEMPO DESDE SALIDA: %d min%n%n" +
        "%s",
        v.getPlaca(),
        v.getPropietario(),
        v.getTipoVehiculo(),
        v.getTipoPlan(),
        v.getRol(),
        v.getArea(),
        r.getHoraSalida(),
        minutos,
        mensaje
    ));

////////////////////// Solo habilitar el botón si puede reingresar GRATIS con FLAT
    btnReingresar.setEnabled(puedeReingresarGratis);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRActionPerformed

    private void btnReingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReingresarActionPerformed

        String placa = txtPlacaR.getText().trim();
    if (placa.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa una placa.");
        return;
    }

/////////////////////// 1) Buscar la ÚLTIMA salida registrada para esa placa
    proyectorparqueo.model.ReciboSalida r =
            proyectorparqueo.model.DatosApp.ultimaSalidaDe(placa);

    if (r == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No hay historial de salida para esta placa.");
        return;
    }

    proyectorparqueo.model.vehiculo v = r.getVehiculo();

    // 2) Validar que el plan sea FLAT
    String plan = (v.getTipoPlan() == null) ? "" : v.getTipoPlan().toUpperCase();
    if (!plan.contains("FLAT")) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "El reingreso solo aplica para vehiculos con PLAN (FLAT)."
        );
        return;
    }

//////////////////////// 3) Validar que no hayan pasado más de 2 horas desde la SALIDA
    java.time.LocalDateTime horaSalida = r.getHoraSalida();
    java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
    long minutosFuera = java.time.Duration.between(horaSalida, ahora).toMinutes();

    if (minutosFuera > 120) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Han pasado mas de 2 horas desde la salida.\n"
              + "El plan FLAT se considera cancelado.\n"
              + "Debes registrarlo como un ingreso nuevo normal."
        );
        return;
    }

/////////////////////// 4) Validar cupo del área donde estaba estacionado
    proyectorparqueo.model.Area area =
            proyectorparqueo.model.DatosApp.getAreaPorNombre(v.getArea());

    if (area != null && area.estaLlena()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay cupo en el area " + area.getNombre() + " para reingresar."
        );
        return;
    }

///////////////////////// 5) Crear NUEVO vehículo con nueva hora de ingreso (ahora)
    proyectorparqueo.model.vehiculo nuevo = new proyectorparqueo.model.vehiculo(
                    v.getPlaca(),
                    v.getPropietario(),
                    v.getTipoVehiculo(),
                    v.getTipoPlan(),
                    true,          // planActivo
                    ahora,         // nueva hora de ingreso
                    v.getRol(),
                    v.getArea()
            );
    
/////////////////////////GUARDA EN MEMORIA
    DatosApp.PARQUEO.registrarVehiculo(nuevo);
    VehiculoDAO.insertar(nuevo); // GUARDARLO EN SQL
    JOptionPane.showMessageDialog(this, "REINGRESO REGISTRADO CORRECTAMENTE");

////////////////////////// 6) Registrar en el parqueo y actualizar ocupación
   // proyectorparqueo.model.DatosApp.PARQUEO.registrarVehiculo(nuevo);
    if (area != null) {
        area.setOcupados(area.getOcupados() + 1);
    }

////////////////////// Importante: ya reingresó, quitarlo de PENDIENTES_FLAT
    proyectorparqueo.model.DatosApp.PENDIENTES_FLAT.remove(nuevo.getPlaca().toUpperCase());

///////////////////////// 7) Mostrar en el área de texto
    java.time.format.DateTimeFormatter f =
            java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    txtAreaR.append(String.format(
            "%n%n✅ Vehículo reingresado:%n" +
            "Placa: %s%n" +
            "Propietario: %s%n" +
            "Plan: %s%n" +
            "Rol: %s | Área: %s%n" +
            "Hora reingreso: %s%n" +
            "Tiempo fuera: %d minutos",
            nuevo.getPlaca(),
            nuevo.getPropietario(),
            nuevo.getTipoPlan(),
            nuevo.getRol(),
            nuevo.getArea(),
            nuevo.getHoraIngreso().format(f),
            minutosFuera
    ));

    javax.swing.JOptionPane.showMessageDialog(this, "Reingreso registrado con éxito.");
    btnReingresar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnBuscarR;
    private javax.swing.JButton btnLimpiarR;
    private javax.swing.JButton btnReingresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlacaR;
    private javax.swing.JLabel lblTituloR;
    private javax.swing.JTextArea txtAreaR;
    private javax.swing.JTextField txtPlacaR;
    // End of variables declaration//GEN-END:variables
}
